- name: local_fs_d
  type: backend.local
  config:
    baseDir: "D:/"

- name: webdav_fs
  type: backend.webdav
  config:
    baseUrl: "http://192.168.242.2:8093"
    username: "zzq"
    password: "********" # Use a secure method to store passwords
    httpOptions:
      connectTimeout: 60s
      receiveTimeout: 60s
      sendTimeout: 60s

- name: metadata_cache_fs
  type: backend.metadata_cache
  config:
    originBackend: webdav_fs
    cacheBackend: local_fs_d
    cacheDir: "/metadata_cache"
    maxCacheAge: "2400h" # 100 days
    largeDirectoryThreshold: 1000 # max cache 1000 items per directory

- name: block_cache_fs
  type: backend.block_cache
  config:
    originBackend: metadata_cache_fs
    cacheBackend: local_fs_d
    cacheDir: "/block_cache"
    blockSize: 1048576 # 1MB
    readAheadBlocks: 2 # Read ahead 2 blocks
    enableReadAhead: false # Enable read-ahead caching

- name: union_fs
  type: backend.union
  config:
    items:
      - backend: local_fs_d
        mountPath: /local_fs_d
      - backend: metadata_cache_fs
        mountPath: /metadata_cache_fs
      - backend: block_cache_fs
        mountPath: /block_cache_fs
      - backend: webdav_fs
        mountPath: /webdav_fs

- name: http_server
  type: frontend.http
  config:
    backend: union_fs
    address: localhost
    port: 8051

- name: request_logger
  type: logger.logger
  config:
    level: info
    format: json
    codeFilenameEnabled: false
    localLogFile:
      logDir: "./req_logs"
      maxFileSize: 536870912 # 512MB
      maxFileCount: 5 # Keep 5 log files

- name: app_logger
  type: logger.logger
  config:
    level: info
    format: json
    localLogFile:
      logDir: "./app_logs"
      maxFileSize: 1073741824 # 1GB
      maxFileCount: 5 # Keep 10 log files

- name: webdav_server
  type: frontend.webdav
  config:
    backend: union_fs
    logger: app_logger
    requestLogger: request_logger
    address: 0.0.0.0
    port: 8052
    authConfig:
      type: basic
      credentials:
        "zzq": "********"

- name: component_diagram
  type: builtin.component_diagram_exporter
  config:
    logger: app_logger
    outputSVGFile: "component_diagram.svg"
    outputPUMLFile: "component_diagram.puml"
