- name: local_fs_d
  type: backend.local
  config:
    baseDir: "D:/"

- name: webdav_fs
  type: backend.webdav
  config:
    baseUrl: "http://192.168.242.2:8093"
    username: "admin"
    password: "test"
    httpOptions:
      connectTimeout: 10s
      receiveTimeout: 10s
      sendTimeout: 10s

- name: metadata_cache_fs
  type: backend.metadata_cache
  config:
    originBackend: webdav_fs
    cacheBackend: local_fs_d
    cacheDir: "/metadata_cache"
    maxCacheAge: "2400h" # 100 days
    largeDirectoryThreshold: 1000 # max cache 1000 items per directory

- name: block_cache_fs
  type: backend.block_cache
  config:
    originBackend: metadata_cache_fs
    cacheBackend: local_fs_d
    cacheDir: "/block_cache"
    blockSize: 4194304 # 4MB
    readAheadBlocks: 2 # Read ahead 2 blocks
    enableReadAhead: true # Enable read-ahead caching

- name: union_fs
  type: backend.union
  config:
    items:
      - backend: local_fs_d
        mountPath: /local_fs_d
      - backend: metadata_cache_fs
        mountPath: /metadata_cache_fs
      - backend: block_cache_fs
        mountPath: /block_cache_fs
      - backend: webdav_fs
        mountPath: /webdav_fs

- name: http_server
  type: frontend.http
  config:
    backend: union_fs
    address: localhost
    port: 8051

- name: webdav_server
  type: frontend.webdav
  config:
    backend: union_fs
    address: 0.0.0.0
    port: 8052
