- name: local_fs_d
  type: backend.local
  config:
    baseDir: "D:/"

- name: local_fs_z
  type: backend.local
  config:
    baseDir: "Z:/"

- name: metadata_cache_fs
  type: backend.metadata_cache
  config:
    originBackend: local_fs_z
    cacheBackend: local_fs_d
    cacheDir: "/metadata_cache"
    maxCacheAge: "2400h" # 100 days
    largeDirectoryThreshold: 1000 # max cache 1000 items per directory

- name: block_cache_fs
  type: backend.block_cache
  config:
    originBackend: metadata_cache_fs
    cacheBackend: local_fs_d
    cacheDir: "/block_cache"
    blockSize: 4194304 # 4MB
    readAheadBlocks: 2 # Read ahead 2 blocks
    enableReadAhead: true # Enable read-ahead caching

- name: union_fs
  type: backend.union
  config:
    items:
      - backend: local_fs_d
        mountPath: /local_fs_d
      - backend: local_fs_z
        mountPath: /local_fs_z
      - backend: metadata_cache_fs
        mountPath: /metadata_cache_fs
      - backend: block_cache_fs
        mountPath: /block_cache_fs

- name: http_server
  type: frontend.http
  config:
    backend: union_fs
