- name: local_fs_d
  type: backend.local
  config:
    baseDir: "D:/"

- name: cache_fs_backend
  type: backend.alias
  config:
    backend: local_fs_d
    subDirectory: /cache

- name: local_fs_z
  type: backend.local
  config:
    baseDir: "Z:/"

- name: cache_fs
  type: backend.block_cache
  config:
    originBackend: local_fs_z
    cacheBackend: cache_fs_backend
    cacheDir: "/"
    blockSize: 4194304 # 4MB

- name: union_fs
  type: backend.union
  config:
    items:
      - backend: local_fs_d
        mountPath: /local_fs_d
      - backend: local_fs_z
        mountPath: /local_fs_z
      - backend: cache_fs_backend
        mountPath: /cache_fs_backend
      - backend: cache_fs
        mountPath: /cache_fs

- name: http_server
  type: frontend.http
  config:
    backend: union_fs
