
- name: local_fs
  type: backend.local
  config:
    base_dir: /data/local_fs

- name: webdav_fs
  type: backend.webdav
  config:
    url: https://example.com/webdav
    username: user
    password: pass

- name: union_fs
  type: backend.union
  config:
    mounts:
      - backend: local_fs
        src: /
        dest: /local
      - backend: webdav_fs
        src: /
        dest: /webdav

- name: cache_fs
  type: backend.cache
  config:
    backend: union_fs
    cache_size: 100MB
    ttl: 3600

- name: logger1
  type: logger
  config:
    level: debug
    format: json
    output: stdout

- name: logger_fs
  type: backend.logger
  config:
    backend: cache_fs
    logger: logger1

- name: http_server
  type: frontend.http
  config:
    backend: logger_fs
    address: "0.0.0.0:8080"
