name: vfs_framework
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

dependencies:
  path: ^1.9.1
  equatable: ^2.0.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
