name: vfs_framework
description: A sample command-line application.
version: 1.0.0
repository: https://github.com/zhangzqs/vfs_framework
publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.8.1

dependencies:
  path: ^1.9.1
  equatable: ^2.0.0
  webdav_client: ^1.2.2
  shelf: ^1.4.2
  yaml: ^3.1.3
  pumli: ^0.1.5
  json_annotation: ^4.9.0
  build_runner: ^2.6.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  json_serializable: ^6.10.0
